### ISSUE TITLE
selecting right to left, the last row is unselectable

### ISSUE THREAD

**Issue by natostanco** [bigfive/atom-sublime-select#100]
Selecting top right, to bottom left. In the case the last line selected is the end of the document ( there are no `\n` ) the last line flickers and is unselectable.

**Comment by signalwerk** [comment]
@natostanco @bigfive This was fixed by #93 but unfortunately the package is still on Version 1.5.1. If you wanna get the fix then you need to get it from the head (for example by doing: `apm install bigfive/atom-sublime-select`). then it works.
