### ISSUE TITLE
Package no longer does anything

### ISSUE THREAD

**Issue by ben-alkov** [bigfive/atom-sublime-select#104]
```
atom version: 1.9.0-beta0 (but this hasn't worked for a while now; at least back into the 1.8.x betas)
Version: 1.5.1
```

Clicking MMB does literally nothing:

```
Mouse Button: Middle
Select Key Trigger: None
```

Setting to

```
Mouse Button: Left
Select Key Trigger: Alt
```

does nothing

_No_ mouse/key combo which I've tried triggers this package for me.

edit:
- FWIW, CTRL-MMB still works to change font size.
- Moving all custom config files aside doesn't help

**Comment by Toreador78** [comment]
Confirmed. It's the same for me, no combination works. I'm on a Windows machine and use version 1.5.1 with Atom 1.9.0-beta0

**Comment by diogosfs** [comment]
I have the same issue with Atom 1.8.0 and package version 1.5.1.

**Comment by dev-marco** [comment]
Confirmed here.
None of the combinations work.
Using version 1.5.1 with Atom 1.9.0-beta0 running on a Windows 10 x64.

**Comment by merikan** [comment]
Same here :-(
Version: 1.5.1
Atom 1.8.0
Mac OSX : 10.11.5

**Comment by MarkHerhold** [comment]
It worked out of the box for me. Same configuration as @merikan 
Version: 1.5.1
Atom: 1.8.0
Mac OSX : 10.11.5

**Comment by ace-han** [comment]
The same issue. I googled it which led me into thread

Version: 1.5.1 
Atom: 1.9.0-beta0
Windows 7

**Comment by tildebyte** [comment]
Can close fixed.
Atom 1.9.2 gold
atom-sublime-select 1.7.2
Win 10 Pro x64

**Comment by thegumbyman** [comment]
Confirming working again as above for:
Atom 1.10.0-beta1
atom-sublime-select 1.7.2
Win 10 Pro x64

**Comment by merikan** [comment]
Can confirm that it's now working.
Version: 1.7.2
Atom 1.9.2
Mac OSX : 10.11.5
