### ISSUE TITLE
Selection of the end of lines

### ISSUE THREAD

**Issue by signalwerk** [bigfive/atom-sublime-select#107]
If I'm at the end of a line and I try to select all the line endings I can do in Sublime Text the following: 

![sublime](https://cloud.githubusercontent.com/assets/992878/17269938/8868f71e-5656-11e6-8a65-928dc001e6cd.gif)

But with this extension it feels broken:

![atom](https://cloud.githubusercontent.com/assets/992878/17269941/a46114a6-5656-11e6-92a8-9df7456dbdd5.gif)

Is that e regression? Hmm... not sure...
#105 is somehow related but not the same. #105 would be a step after this I guess.

**Comment by morbius1st** [comment]
I have the same issue.  
Version: 1.6.0
Atom: 1.8.0

**Comment by Ingramz** [comment]
It used to work before #93 was merged.

**Comment by pratyushtewari** [comment]
Seems like a regression. It used to work before.

**Comment by jayveeee** [comment]
I have the same issue.
Version: 1.7.2
OS: Windows
Atom: 1.9.8

**Comment by jarednipper** [comment]
To others having this issue, a quick workaround is to comment out `editor-handler.coffee` line 120. `(if rowLength > @mouseStartPos.column or rowLength > @mouseEndPos.column)`

https://github.com/bigfive/atom-sublime-select/blob/master/lib/editor-handler.coffee#L120

I haven't experienced any side effects yet.

**Comment by jeromegrosse** [comment]
I've been using the 'fix' mentioned by @jarednipper and I confirm that it fixes the issue.

**Comment by elijahgagne** [comment]
I'm also seeing this problem with:
Version: 1.7.2
OS: Windows
Atom: 1.12.5

I'm not having luck with jarednipper's workaround. If I comment out just line 120, the package fails to load. If I comment out lines 120-122, column mode no longer works at all.

**Comment by simplesteph** [comment]
@jarednipper can you please do a PR so we can all benefit from it?

**Comment by jarednipper** [comment]
@simplesteph I don't know enough about this project to know what this hack breaks. Also, a Windows user reported that it didn't help.

**Comment by bigfive** [comment]
Yep definite bug. Thanks for the reports everyone. I'll fix this one in the next release

**Comment by aaranmcguire** [comment]
So, I've just attempted @jarednipper's fix and found some undesired behaviour:

Before:
```coffee
        for row in [@mouseStartPos.row..@mouseEndPos.row]
          @mouseEndPos.column = 0 if @mouseEndPos.column < 0
          rowLength = @editor.lineTextForScreenRow(row).length
          if rowLength > @mouseStartPos.column or rowLength > @mouseEndPos.column
            range = [[row, @mouseStartPos.column], [row, @mouseEndPos.column]]
            ranges.push range
```

After:
```coffee
        for row in [@mouseStartPos.row..@mouseEndPos.row]
          @mouseEndPos.column = 0 if @mouseEndPos.column < 0
          rowLength = @editor.lineTextForScreenRow(row).length
          # if rowLength > @mouseStartPos.column or rowLength > @mouseEndPos.column
          range = [[row, @mouseStartPos.column], [row, @mouseEndPos.column]]
          ranges.push range
```

I've found this causes highlighting of lines that should not be selected (easier to show than explain).

Before (Notice Line 6 + 8 are not selected): 
<img width="258" alt="screen shot 2017-03-12 at 10 04 12" src="https://cloud.githubusercontent.com/assets/1158370/23830844/e3c1f74e-070b-11e7-827a-759cc21e61ea.png">

After (Notice Line 6 + 8 are selected):
<img width="163" alt="screen shot 2017-03-12 at 10 02 15" src="https://cloud.githubusercontent.com/assets/1158370/23830856/099f3af8-070c-11e7-94c5-b48826e3a8a3.png">

And for reference, here's a screenshot from Sublime Text:
<img width="138" alt="screen shot 2017-03-12 at 10 02 38" src="https://cloud.githubusercontent.com/assets/1158370/23830860/2da04050-070c-11e7-8000-0cfb74dd23de.png">

Hope this helps.

**Comment by bigfive** [comment]
Hey everyone.
Ive just released a patch for this. Please let me know how you go.

**Comment by aaranmcguire** [comment]
I guess its fixed in that you no longer need to do the workaround, but you still have the issue I mentioned above. - It won't affect many people, but  it would be a nice feature to maintain.
