### ISSUE TITLE
selection not working

### ISSUE THREAD

**Issue by jagadeeshvarma** [bigfive/atom-sublime-select#110]
Hi,

This feature worked till yesterday. But I don't know what happened it stopped working. I tried reinstalling the package and then Atom itself, still no luck. Please help.

Thanks
Jagadeesh

**Comment by albireox** [comment]
I'm having a similar problem when I open Atom. If I then disable and re-enable atom-sublime-select it seem to go back to working fine.

**Comment by RishiKulshreshtha** [comment]
This seems as fixed in the current release:

I'm using:

- atom v1.9.2
- atom-sublime-select v1.7.2

and its working totally fine at my end.

Please try to update your package https://github.com/bigfive/atom-sublime-select/releases/tag/v1.7.2

**Comment by jagadeeshvarma** [comment]
Updated atom-sublime-select v1.7.2 and it's working now.
Thanks @RishiKulshreshtha
