### ISSUE TITLE
Select not work on end line and with softwrap

### ISSUE THREAD

**Issue by dimensi** [bigfive/atom-sublime-select#113]
My English is poor, I'll show you all the best in the pictures)
Compare'll be with **Brackets**.
1. **Atom**
 ![default](https://cloud.githubusercontent.com/assets/11390039/17838687/b11ba26a-67db-11e6-8229-f73c05461c22.gif)
Now **Brackets**
![brackets](https://cloud.githubusercontent.com/assets/11390039/17838695/e34adddc-67db-11e6-9104-31428c047982.gif)
Now bug with softwrap
**Atom**
![atom](https://cloud.githubusercontent.com/assets/11390039/17838721/11b5ab7a-67dc-11e6-80db-61db47ff4c8b.gif)
**Brackets**
![brackets1](https://cloud.githubusercontent.com/assets/11390039/17838744/62c8218c-67dc-11e6-9d64-e996aa07cb0d.gif)
As can be seen in gif file, I can not clean off the excess tab in Atom.
Thank you in advance.

**Comment by bigfive** [comment]
Duplicate https://github.com/bigfive/atom-sublime-select/issues/101
