### ISSUE TITLE
Busted behavior for really simple case

### ISSUE THREAD

**Issue by jacquescrocker** [bigfive/atom-sublime-select#117]
When trying to remove a single indent space from a block...
![](https://cl.ly/0x2R3M0J4514/content)

This is with a fairly clean Atom install, using 1.10.1 and latest of atom-sublime-select

Let me know if I'm doing something wrong

**Comment by Hazzard13** [comment]
Not a fix to the package, but atom has a built-in shortcut for this. Make a selection, and the shortcuts are tab to add an indent to the block selection, and shift-tab to remove an indent. Which'll always be easier than doing it with column selection anyway.

**Comment by bigfive** [comment]
I feel your pain.
This is an issue with the way atom handles multiple cursors when you have a mixture of spaces and soft-tabs. I don't think there is anything I can do in this package to help. Perhaps bring it up with Atom?

One work around is to create a column of cursors, option-right to the next non-whitespace character, go back one char, then hit delete. Like this:

![example-fix](https://cloud.githubusercontent.com/assets/633193/22850740/0c001278-f04a-11e6-860b-18d057e8798d.gif)
