### ISSUE TITLE
vertical multiline insert behaves badly with autoindent when inserting tab

### ISSUE THREAD

**Issue by fbenavides69** [bigfive/atom-sublime-select#124]
When adding a tab for multiple lines, and there are several indents, adding a tab displaces the alignment from left to right, miss-aligning every thing.
![beforeaddingtab](https://cloud.githubusercontent.com/assets/4228155/20015522/2e0dfdd6-a292-11e6-86f2-6b2cc3b3e03c.png)
![afteraddingtab](https://cloud.githubusercontent.com/assets/4228155/20015539/3b9f4da6-a292-11e6-9589-a45e73e3ad81.png)

**Comment by bigfive** [comment]
Sorry, this is a bug with how atom handles multiple cursors. This package just help placing the cursors, not the behaviour of them once created. Perhaps lodge a bug report in with Atom.
