### ISSUE TITLE
Can you increase the shortcut key support? Need mouse in Mac

### ISSUE THREAD

**Issue by tomoat** [bigfive/atom-sublime-select#128]
Can you increase the shortcut key support? Need mouse in Mac

example: cmd+option+down

**Comment by ozak** [comment]
+1

**Comment by bigfive** [comment]
Atom already has support for selecting multiple lines outside of this package. Default is `ctrl-shift-up` and `ctrl-shift-down`, which as you say interferes with mission control by default. You can edit this in your key map tho.
As I say, not part of this package tho, its part of Atom proper.
