### ISSUE TITLE
Select end of line

### ISSUE THREAD

**Issue by alias1** [bigfive/atom-sublime-select#129]
Currently, if I try to select at the end of the line (beyond the end of the line) it just doesn't select.

I can work around this by selecting the start of the line, then pressing the end key; but it would be nice to not have to.

**Comment by simplesteph** [comment]
+1 
I'm expecting to click further after the end of the click using alt key, and dragging down, to select at the end of the line for multiple lines

**Comment by bigfive** [comment]
Not sure if I understand this one. Can you show a screenshot/gif of the issue or describe it in more detail?

**Comment by alias1** [comment]
Will try to describe, and if not, look into gif/etc.

So basically I want to be able to make a multi-line column selection, but instead of being at the start/in the middle of the lines, I want to do it at the end.

In sublime, if I 'draw' my selection line beyond the end of the text, it would put all of the cursors at the end of each line. Whereas that doesn't (or at least didn't when I raised this, can't check at the moment) happen with this plugin.

A rudimentary attempt to show it in ascii:
'''
#             . < Draw column select line from here
AAAA|
BB|
CCCCCCCC|
'''

Where '|' represents the cursor

**Comment by bigfive** [comment]
Ah yep yep. I think this used to work but has regressed. I'll look into it

**Comment by bigfive** [comment]
Related to https://github.com/bigfive/atom-sublime-select/issues/107

**Comment by alias1** [comment]
Awesome, thanks!

Get Outlook for iOS




On Tue, Feb 14, 2017 at 4:29 PM +1100, "Jonathan Williams (jdub)" <notifications@github.com> wrote:












Ah yep yep. I think this used to work but has regressed. I'll look into it

**Comment by bigfive** [comment]
Ive just patched this. Let me know how you go
