### ISSUE TITLE
Column selection with keyboard (no mouse) seems broken

### ISSUE THREAD

**Issue by rkranendonk** [bigfive/atom-sublime-select#130]
Used to be, I could use Shift-Alt-Arrow to make a column selection. 
Not at the moment.

macOS Sierra 10.12.1, Atom 1.12.6, Column Selection 1.7.2

**Comment by bigfive** [comment]
Hi @rkranendonk, The feature you describe (using your keyboard to make selections) is actually part of Atom, not part of this package. This package purely deals with multiline selections while dragging your mouse.
