### ISSUE TITLE
Deprecated call: TextEditor.prototype.displayBuffer (Atom 1.13.0)

### ISSUE THREAD

**Issue by bkeating** [bigfive/atom-sublime-select#133]
I'm running Atom 1.13.0 which removes `TextEditor.prototype.displayBuffer`. Here's the error Atom spits out:

> `TextEditor.prototype.displayBuffer` has always been private, but now it is gone. Reading the `displayBuffer` property now returns a reference to the containing `TextEditor`, which now provides some of the API of the defunct `DisplayBuffer` class.
```
* TextEditor.get - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:101:14  

* SublimeSelectEditorHandler._setup_vars - /Users/bpk/.atom/packages/Sublime-Style-Column-Selection/lib/editor-handler.coffee:100:40  

* new SublimeSelectEditorHandler - /Users/bpk/.atom/packages/Sublime-Style-Column-Selection/lib/editor-handler.coffee:17:12  

* module.exports.switch_editor_handler - /Users/bpk/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:136:34  

* Function.module.exports.Emitter.simpleDispatch - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14  

* Emitter.emit - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28  
```

Invoking a block select now obviously crashes the package and atom. Not sure how to fix this myself yet, but thought I'd report it.

**Comment by KevinNadaud** [comment]
I have this bug too since the update to 1.13. 
I have sometimes crash of the editor in addition if this plugin is enable (I has no crash before th update).

**Comment by brandonforce** [comment]
I am having this issue as well, as of today. Is there a solution?

**Comment by monsieurnebo** [comment]
Same issue here, could you take a look please ? :)

**Comment by jkdv** [comment]
Any ETA?

**Comment by d4rkd0s** [comment]
Also see #137 #138

**Comment by srissel** [comment]
Is this addon still maintained?

**Comment by monsieurnebo** [comment]
@srissel Last fixed issues & commits are 6 months old so ... It's doesn't seems so.

**Comment by srissel** [comment]
It's a pity that there doesn't seem to be an alternative addon available.
Maybe someone could fork this one and take care of the deprecation?

I'd do this on my own, since often deprecations are not that difficult to
refactor. Unfortunately I'm not familiar with addon development for Atom....

2017-01-25 9:42 GMT+01:00 Cyril BONNET <notifications@github.com>:

**Comment by jpwalters** [comment]
I'm still getting this error/warning message occasionally but at least with version 1.13.1 the editor is not crashing for me.

**Comment by d4rkd0s** [comment]
@srissel I'm in the same boat as you. Would love to help, not sure how Atom Addon dev'ing works, and I wouldn't be the ideal person to re-maintain a project like this.

**Comment by shdobxr** [comment]
Same boat as you all. Typically I can reproduce crashing when editing Json files and making vertical selections  where the vertical plane is not straight but with numerous indentations and spacing the JSON requires.

**Comment by mjbrender** [comment]
I'm alongside you all. @bigfive, we're huge fans of your work on this plugin. Anything we can do to help this issue along (while also being unfamiliar with the code)? Thank you!

**Comment by bkeating** [comment]
Is this an Electron-level change (deprecating displayBuffer?) I'm also
unfamiliar, but we can probably start to narrow it down a bit.

What other packages out there have had similar issue? Maybe we can examine
how they dealt with this deprecation.
