### ISSUE TITLE
Atom crashes when selection involves a shorter line

### ISSUE THREAD

**Issue by kalsan** [bigfive/atom-sublime-select#134]
Given a text of the form:
```
11111111111111111111000000000000000
11111111111111111111
11111111111111111111000000000000000
```
where I wrote `1` to represent characters present in all lines and `0` for denoting characters in lines that are longer than the lines just composed of `1`s, **Atom will crash** when selecting across `0`s.

In other words: The editor crashes when selecting across lines that are so short that they have no text under the selection cursor.

The bug was introduced in the last 2 weeks I think.

This is actually harder to formulate than I thought. I hope it's clear this way and I'm happy to re-explain otherwise.

**Comment by bpjones** [comment]
Invoking this add-in using Atom >= 1.13 causes Atom to crash (caused by bug #133).  Your use case looks more specific though.

**Comment by bigfive** [comment]
@kalsan can you please update and recheck your issue

**Comment by kalsan** [comment]
Thanks for the fix! Cannot reproduce no longer. Closing.
