### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by ghoetker** [bigfive/atom-sublime-select#151]
Hi. Trying to install on 1.23.0-beta1 on MacOS 10.13.1.  Getting the following error. Please let me know if I can provide additional error.  If issue is that I'm using a beta version, I totally get it.  Thanks!

```
Installing “Sublime-Style-Column-Selection@1.7.4” failed.Hide output…
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/ghoetker/.atom/packages/Sublime-Style-Column-Selection/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom Beta.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by sleeve** [comment]
Seeing the same issue on Atom 1.23.1 x64 on MacOS 10.13.2.

**Comment by ghoetker** [comment]
Oddly, installation from the command line via `apm` seems to work just fine.

**Comment by garethallenstringer** [comment]
I am having the same issue in which I cannot install on Atom version 1.23.1 x64 on Windows 10

@ghoetker I also can't install with apm either

**Comment by montykamath** [comment]
I have the same problem.  1.23.1 on MacOS 10.13.1.  I cannot install via the Ui or apm.  Same error in both places.

**Comment by TomJahncke** [comment]
Same problem

**Comment by nikolalkc** [comment]
I have the same problem

**Comment by keyhan** [comment]
I had same problem, installed it manually and it works.

**Comment by mnikogit** [comment]
OS window7 with the same problem!

**Comment by binbjz** [comment]
+1 on mac pro

**Comment by MR158** [comment]
I solved the problem after installing nodejs and python

**Comment by craftykate** [comment]
I had the same issue with the same error (on Mac OS 10.12.6) but installing with apm worked perfectly. `apm install sublime-style-column-selection`

**Comment by gkrash** [comment]
not sure if this helps or not... but I found that:
`apm install sublime-style-column-selection` works fine, while
`apm install Sublime-Style-Column-Selection` failed with the error above (and fails for me in the app)

It *appears* that the issue is maybe in `package.json` - that's the only place I can see where that particular string is.  Hasn't been touched in a while, but maybe something changed with how it works between the GUI installer and the web interface..  I'd offer a patch, changing that name to all lowercase, but I'm honestly not sure how to test it since it works locally..

**Comment by marcwiest** [comment]
Had the same problem ... then simply create the folder (Sublime-Style-Column-Selection) within /Users/username/.atom/packages and thereafter was able to install the package.

**Comment by bkeating** [comment]
Neither `apm install sublime-style-column-selection` nor manually creating the dir `./atom/packages/Sublime-Style-Column-Selection` did it for me. 

What worked was downloading this repo as a zip and unzipping to the manually created dir above. 

I did not inspect the console--on the run, but thought I'd mention this hear to add to variations.

**Comment by bigfive** [comment]
Sorry, I took a bit of a hiatus from maintaining this.

I cant seem to replicate this issue now, though I don't have access to some of the operating systems reported. Does anyone have the issue currently? You might be able to test it by uninstalling and reinstalling through the package manager

**Comment by ghoetker** [comment]
I appear to have successfully installed in the interim.  Not sure how at this point, but all seems to be working.  MacOS. Thank you.

_______________________________________

Glenn Hoetker
Professor in Business Strategy

Melbourne Business School, University of Melbourne
200 Leicester Street, Carlton, Victoria 3053, Australia
Email: Glenn.Hoetker@mbs.edu<mailto:Glenn.Hoetker@mbs.edu>

[cid:image007.jpg@01D37974.EE7C09F0]


I acknowledge the Traditional Owners of the land on which I work, the Wurundjeri people of the Kulin Nations, and pay my respects to their Elders, past and present.

On 28 Sep 2018, at 5:59 pm, Jonathan Williams (jdub) <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I took a bit of a hiatus from maintaining this.

I cant seem to replicate this issue now, though I don't have access to some of the operating systems reported. Does anyone have the issue currently? You might be able to test it by uninstalling and reinstalling through the package manager

**Comment by 007Alice** [comment]
> I had same problem, installed it manually and it works. Just download the zip from here and unpack it in the packages directory of atom, then restart Atom.

It works, thank you.
