### ISSUE TITLE
Cursor jumping to above lines when selecting

### ISSUE THREAD

**Issue by werunom** [bigfive/atom-sublime-select#155]
When I attempt to select a column of text by `ctrl+left-click`, the cursor jumps from the present line to some line above. Below is the gif for the same.

![jumping cursor](https://user-images.githubusercontent.com/24664855/35735920-536afa4a-084c-11e8-94fc-a631572712ef.gif)

The same thing happens even when I change the hotkey. Also, I had disabled most of the relevant installed packages while reproducing this. 

Atom version - 1.23.3
OS - manjaro linux

**Comment by werunom** [comment]
I did tried this with three kinds of scenarios. Below gif illustrates those three situations. Only in the last one, the cursor jumps without doing column selection. 

![jumping cursors 2](https://user-images.githubusercontent.com/24664855/35762395-cedd2f30-08bb-11e8-9172-d5c23d335799.gif)

**Comment by daeh** [comment]
same issue but cursor jumps to end of document. essentially makes the package unusable, which is such a shame as it's one of the functionalities that I use the most in sublime.

**Comment by v1-hermit** [comment]
@bigfive has not a single activity for more than a year already. Probably he's no longer the earth. Everyone we have to dissolve now, bye.

**Comment by bigfive** [comment]
Hey. I've been a busy guy lately (2 kids under 5)

If you would like to contribute feel free, ill even give you (or anyone
else who is interested) write access to the repo if you would like to help
maintain the addon.

On 24 Apr. 2018 3:28 pm, "v1-hermit" <notifications@github.com> wrote:

@bigfive <https://github.com/bigfive> has not a single activity for more
than a year already. Probably he's no longer the earth. Everyone we have to
dissolve now, bye.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bigfive/atom-sublime-select/issues/155#issuecomment-383831664>,
or mute the thread

**Comment by snowcity-cn** [comment]
I'd like to help but I don't have the ability. Give the access to another one who can fix the problem please.

**Comment by daeh** [comment]
thanks, @bencooling. I'm sad to lose option-click-drag multi-cursor looks like the best atom has to offer atm.

**Comment by andrei-elizaga** [comment]
@bigfive , I'm interested in looking for a fix to this.  Where do you think we should start checking?

**Comment by snow212-cn** [comment]
@bigfive, you're **free** enough to be busy with this repo [ExMachina](https://github.com/bigfive/ExMachina), and would rather ignore [atom-sublime-select](https://github.com/bigfive/atom-sublime-select), even when here's someone instrested in it. You've been a real busy guy!

**Comment by snow212-cn** [comment]
@bigfive, you're **free** enough to be busy with this repo [ExMachina](https://github.com/bigfive/ExMachina), and would rather ignore [atom-sublime-select](https://github.com/bigfive/atom-sublime-select), even when here's someone instrested in it. You've been a real busy guy!

**Comment by bigfive** [comment]
^ found the stalker ;)

OK, consider me bullied into giving this a go. 
I imagine its to do with how I'm converting the cursor position into line/character position. It obviously breaks when theres a long line above the place you are selecting and you have line wrapping on. 
I'll see what I can do, maybe atom has recently added some helpful API functions I can use.

**Comment by bigfive** [comment]
@werunom Ive just released a new patch for this. Let me know if it fixes the issue for you.
Thanks for your patience :)
