### ISSUE TITLE
Column mode "sticks"

### ISSUE THREAD

**Issue by mark-hahn** [bigfive/atom-sublime-select#17]
I'm having an intermittent but frequent problem.  When I finish using column mode the selection sticks in column mode and I can't do normal selection.  It acts as if the alt-key is stuck down.  The only thing that fixes it is to select again with the alt key down although this takes several tries at times.

I saw the thread here about the mouse leaving the window but this problem happens when the cursor doesn't leave the middle of the window.

I'm on windows 8.0 and atom 119.  This has happened since I started with atom a few weeks ago at version 116.

**Comment by bigfive** [comment]
Is this now fixed for you? I can no longer reproduce the issue?
