### ISSUE TITLE
Incorrect cursor position with seti-syntax

### ISSUE THREAD

**Issue by freshyill** [bigfive/atom-sublime-select#21]
I'm having an issue with seti-syntax and [atom-sublime-select](https://github.com/jesseweed/seti-syntax/). When doing a vertical selection of text or individual multi-line selections, the selection is inserted to the right of the cursor.

The gif explains it pretty well.

![text selection](https://cloud.githubusercontent.com/assets/879292/3966606/f83e4770-27a4-11e4-8ca2-f95d6f3567f2.gif)

I'm posting this on seti-syntax's issues as well.

**Comment by bigfive** [comment]
I believe this is now resolved as I use a more native way of getting the character width. Can anyone confirm?

**Comment by freshyill** [comment]
Seems to be working perfectly now, thanks!
