### ISSUE TITLE
Not working in Atom 137 and 138 on Windows.

### ISSUE THREAD

**Issue by gerane** [bigfive/atom-sublime-select#25]
It just isn't working at all. Can't get the block selection to trigger.

**Comment by bigfive** [comment]
Hmm. I guess this will be fixed when I implement configurable key options

**Comment by bigfive** [comment]
Let me know if the latest patch helps. Its not configurable but it has more sensible windows key config

**Comment by papermoon1978** [comment]
Doesn't work for me either > version 1.2.3 on Windows 7 atom 177. Maybe the issue is because the alt key triggers the menu bar? When I change it to 

 when 'win32'
    key: 'shiftKey'
    mouse: 1
    middleMouse: true

if works fine for me (when holding shift of course - but that's fine)

**Comment by bigfive** [comment]
Keys are now configurable
