### ISSUE TITLE
Not working on Windows 8.1 - Atom 0.155

### ISSUE THREAD

**Issue by pistou** [bigfive/atom-sublime-select#28]
I have no idea why, but it's not working for me (WIndows 8.1 64bit)

I've tried with the "deprecated version" (https://atom.io/packages/SublimeSelect) and it works perfectly fine.

**Comment by HKRnew** [comment]
Not work here to. Ubuntu 14.04, Atom 0.177.0

**Comment by Haacked** [comment]
Doesn't work for me either on Windows 8.1

**Comment by bigfive** [comment]
I don't have a windows box to test this on. Anyone else have a solution for this that could provide a PR?

**Comment by PhiLhoSoft** [comment]
For the record, this works fine with Atom 1.x on various Windows boxes (7, 10) I tried it on.
Given the age of Atom 0.x, perhaps this bug can be closed... :smile:

**Comment by Haacked** [comment]
Hmm, didn't work for me on Atom 1.9 and Windows 10.
