### ISSUE TITLE
Missing cursor indicator

### ISSUE THREAD

**Issue by sadovnychyi** [bigfive/atom-sublime-select#33]
In ST, cursor is visible on selected area, it makes it easier to detect the selected area.
![image](https://cloud.githubusercontent.com/assets/193864/5852153/18d9461a-a24d-11e4-947d-e89a1c841137.png)
No cursor in atom:
![image](https://cloud.githubusercontent.com/assets/193864/5852157/204a45d4-a24d-11e4-9841-96eac08a8db2.png)

**Comment by bigfive** [comment]
This is actually a sistemic issue of atom. Their selection implementation doesn't show end cursors.
I wont fix this.
