### ISSUE TITLE
Dragging past last line extends selections to the right

### ISSUE THREAD

**Issue by dvlsg** [bigfive/atom-sublime-select#38]
When using the multiple selection mouse dragging, if you drag underneath the bottom-most line, all selections will extend horizontally to the right, to the end of each line. In sublime, the width of the selection will remain dependent on the horizontal position of the mouse, even when the cursor is past the last line, and will not automatically extend to the end of the line.

Not sure if this is a bug from your perspective or not, but it does differ from how sublime acts currently. Not a huge deal, either. I can provide gifs or video, if this description isn't enough.

**Comment by jberthet** [comment]
Hello,

Got a similar bug, it has effect when lines before or after the selection are empty.

You can see an example on the image below. The bug could be very annoying on real code editing.

![untitled_-_atom](https://cloud.githubusercontent.com/assets/2607906/6505425/5f00f91a-c342-11e4-9401-e5ef4680b290.png)

Atom version: 0.186.0
Package version: 1.2.3

Regards.

**Comment by bigfive** [comment]
I might be able to cancel all mouse events when dragging outside of the pane. That should stop this
