### ISSUE TITLE
First or last line selecting inconsistently when dragging in certain directions

### ISSUE THREAD

**Issue by Tedko** [bigfive/atom-sublime-select#40]
http://i.imgur.com/1TVfet3.gif

![untitled](https://cloud.githubusercontent.com/assets/6687437/6741547/5c568fd0-ce56-11e4-8fa2-a1b462b23f13.gif)

see the last 5seconds

**Comment by jethrolarson** [comment]
I'm also getting this error consistently
OSX 10.9.5, Atom 0.188, sublime-style-column-selection 1.2.3

**Comment by Tedko** [comment]
@jethrolarson  
yes, for me alt-drag will cause this bug.

**Comment by bigfive** [comment]
Yep, I can reproduce this bug, thanks for the clarity @jethrolarson. I'll have a look at it today.

**Comment by vorg** [comment]
I'm getting the same bug also only when selecting to the left:

![9jhwv2swbp](https://cloud.githubusercontent.com/assets/171001/9815360/4bd7194c-588d-11e5-8d54-80674ec9442e.gif)

**Comment by RyanZim** [comment]
@bigfive Wasn't this fixed by #93?

**Comment by signalwerk** [comment]
@RyanZim @bigfive This was fixed by #93 but unfortunately the package is still on Version 1.5.1. If you wanna get the fix then you need to get it from the head (for example by doing: `apm install bigfive/atom-sublime-select`). then it works.

**Comment by RyanZim** [comment]
>  the package is still on Version 1.5.1.

A new version has been released, @Tedko @bigfive can you close?

**Comment by Tedko** [comment]
@RyanZim Thanks. It can be closed now. 

;)

**Comment by RyanZim** [comment]
@Tedko I can't close it, can you?
