### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pixelPositionForMouseEvent' of null

### ISSUE THREAD

**Issue by s2t2** [bigfive/atom-sublime-select#63]
[Enter steps to reproduce below:]

1. alt-click and drag down vertically

**Atom Version**: 1.0.0
**System**: Mac OS X 10.9.5
**Thrown From**: [Sublime-Style-Column-Selection](https://github.com/bigfive/atom-sublime-select) package, v1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForMouseEvent' of null

```
At /Users/s2t2/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:85

TypeError: Cannot read property 'pixelPositionForMouseEvent' of null
  at _screenPositionForMouseEvent (/Users/s2t2/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:85:41)
  at atom-text-editor.onMouseDown (/Users/s2t2/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:53:25)

```

### Commands

```
     -1:12.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:12.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:12.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:09.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:07.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:05.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:03.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:02.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:00.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:59.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:55.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:54.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:53.7.0 core:undo (atom-text-editor.editor.is-focused)
  4x -0:40.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.9.0 core:copy (a.btn-copy-report.icon.icon-clippy)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
minimap, v4.10.0

# Dev
No dev packages
```

**Comment by Kerosene2000** [comment]
:+1:

**Comment by llagerlof** [comment]
When I installed this package(1.3.0) a few days ago it was working, now I am receiving this same error. 

Maybe it's useful I tell this strange thing that happened when I tried to uninstall this package. When I uninstall the "atom-sublime-select", I tried to ALT-click-and-drag to verify if the error persist, but no, the error is gone and the column selection functionality worked! So I tried to restart Atom, and the functionality now is gone.

**Comment by MartinMuzatko** [comment]
When this error is thrown, the vertical selection doesn't work in files of the same type (in my case: less files)
Restarting Atom temporarily fixes the problem.

**Comment by ryanspice** [comment]
:thumbsup:

**Comment by chrwi** [comment]
This also happens on my Windows 7 x64, Atom 1.0.11

**Comment by xplusplus** [comment]
Also getting on Server 2012 R2, Atom 1.0.19, expect Atom said it was being thrown from atom-material-syntax. My callstack and other info is on this thread: https://github.com/silvestreh/atom-material-syntax/issues/17#issuecomment-150710925

**Comment by bigfive** [comment]
I believe this is fixed in the new version. Thanks for your patience on this folks
