### ISSUE TITLE
Improve the readme. Include default platform keys and how to configure

### ISSUE THREAD

**Issue by mainameiz** [bigfive/atom-sublime-select#66]
Please add info to README of how it works

**Comment by thinsoldier** [comment]
Yes please. The forum post that told me about it says to use alt+drag / option+drag but that does nothing.

There seems to be a default ability to make rectangular selections with the middle mouse button but I often use a trackpad that can't simulate a middle mouse button.

**Comment by ricsdeol** [comment]
:+1:

**Comment by AndiDog** [comment]
Yes, it's not clear at all even when looking at the source. Tried on Ubuntu and shift + right-drag gives me the context menu while shift + middle-drag does vertical selection but then inserts the clipboard because that's what the middle mouse button does. So I still don't know how to use it.

**Comment by bigfive** [comment]
A PR for the readme update would be fantastic. We now have more sensible defaults for linux and configurable keys, but you are correct, the default key combinations for each platform, and instructions on how to customise them should be in the readme

**Comment by hgoodman** [comment]
Another suggestion for the README...

I'm trying to understand the difference between this column select package and Atom's default column select (triggered by Ctrl+Alt on Windows). Any chance that could be added? Should this question be entered as a separate issue?
