### ISSUE TITLE
random pastes when selecting

### ISSUE THREAD

**Issue by SlimeQ** [bigfive/atom-sublime-select#68]
when using this multiselect, whatever is in the clipboard is automatically pasted to each cursor. i'm on ubuntu 14.04

update:

this is happening because middle click is mapped to paste by default... this is ridiculous behaviour. unsure how to change it

**Comment by austincummings** [comment]
:+1: having the same issue.

**Comment by matt-della** [comment]
The middle mouse in Linux pastes whatever is highlighted, which means that using the middle mouse for something like this would cause major issues. Using your normal mouse button, if possible (I'm still figuring out how to do that), would fix it.

**Comment by jhealy86** [comment]
Having this issue as well, and I think @matt-della has a good solution for it. Why is this package assigning a behavior to a key that already has a default behavior in that operating system? It really should be changed to be altKey by default.

**Comment by matt-della** [comment]
@jhealy86 I realized that Linux systems often assign the alt key to move windows around the screen, so using the alt key would also be sub-optimal. However, I do believe that properly configuring either alt-shift or ctrl-shift to override the shift key behavior *should* work.

**Comment by jhealy86** [comment]
I just changed mine to ctrlKey, and you do lose Linux's multi-select with that, but I've honestly never used that feature, and Atom has other (better) ways to do it. So I think that's what I'm going to stick with.

**Comment by bigfive** [comment]
As noted, this was due to the way ubuntu pastes using middle mouse button. This is now configurable.
