### ISSUE TITLE
Hardcoded trigger key (alt) conflicts with atom-ctags

### ISSUE THREAD

**Issue by arielpontes** [bigfive/atom-sublime-select#69]
This is a problem that could be solved both on the `atom-sublime-select` or on the `atom-ctags` side (ideally both, god knows how many other conflicting packages exist out there). `alt+click` triggers a symbol search when ctags is enabled, so I can't select columns of text anymore. Ideally the key (or key combination) should be configurable. The solution I found for now was changing the source and replacing "altKey" with "metaKey" for darwin (I'm on a Mac).

**Comment by datnordstrom** [comment]
1+

**Comment by infinityzx** [comment]
Same issue on linux, due to the "mnemonic" gtk feature, which even if forced to be disabled, still overrides the alt key in atom.
Would definitely help if you can change the trigger with something like CTRL+ALT+SELECTION or better let the user the option to bind any preferred key

**Comment by bedge** [comment]
+1

**Comment by pstrangwrzekle** [comment]
+1

**Comment by rubencaro** [comment]
+1, configurable if possible please

**Comment by mjs7231** [comment]
+1 this is unusable on Linux until solved. :(

**Comment by bigfive** [comment]
Keys are now configurable. thanks for your patience on this folks
