### ISSUE TITLE
How do I integrate this into atom?

### ISSUE THREAD

**Issue by elinxie** [bigfive/atom-sublime-select#72]
I have a .coffee file. How do I take what I pulled to getting the functionality to work?

**Comment by alexhicks** [comment]
If you're talking about making changes to a package have a read of: https://atom.io/docs/v1.2.3/hacking-atom-tools-of-the-trade

If you've pulled this package you will need to link it as a development package for your changes to override the installed package. You can do this by opening a terminal window and moving into your new directory and running `apm link --dev` then opening atom in dev mode with `atom --dev`

For live updates after getting atom to use your development package you will need to reload atom with the `Window: Reload` command found in atom's command palette
