### ISSUE TITLE
sublime-style-column-selection cannot work properly after activate atom-html-preview pulgin.

### ISSUE THREAD

**Issue by JeOam** [bigfive/atom-sublime-select#75]
I am using these two atom plugin simultaneously, but once i activate atom-html-preview,  sublime-style-column-selection cannot work properly

* sublime-style-column-selection 1.3.0
* [atom-html-preview](https://atom.io/packages/atom-html-preview) 0.1.13
* Mac OS X EI Capitain
* Atom 1.2.1

I have to restart atom to handle this problem.

**Comment by moospit** [comment]
+1, I am having same issues with 

* sublime-style-column-selection 1.3.0
* markdown-preview 0.156.0
* Windows 7 and Windows 10
* Atom 1.2.4

The selection works fine until the preview is opened. After that the selection only works on the end of lines and the viewpoint and selection marker *jumps* from the original point of selection.

Closing the markdown-prewiev doesn't solve this issue. For handling this atom needs a restart.

**Comment by bigfive** [comment]
Yeah, the package only supports selecting text in an editor pane. What is the markdown preview package you are using, I'll see if I can make sure the package does even activate if you are using a markdown preview pane?

**Comment by bigfive** [comment]
I believe this should work with the new release

**Comment by JeOam** [comment]
@bigfive Thank you so much, It works! :)

**Comment by gtaifu** [comment]
@bigfive  Thank you! It indeed works!!
