### ISSUE TITLE
option shift arrow to select by words in multiple lines

### ISSUE THREAD

**Issue by sonarism** [bigfive/atom-sublime-select#77]
on mac

option shift arrow (Left/Right) selects by word 
(option arrow is to move cursor by word)

but when i try the same command with multi line selected, it only selects the last one..

i use this a lot to recreate json, objects etc so it'd be helpful if someone can fix it.

**Comment by bigfive** [comment]
Thats a bug in Atom. This package doesn't add multiline selections to atom (that already exists), it just adds the ability to _create_ selections by dragging. Perhaps raise the issue with atom?

**Comment by optimusama** [comment]
actually i've found a work around:
on mac go to setting end select Ctrl for Select Key Trigger

Ctrl + Opt + Shift + Arrow 
works kind of like how sublime would work

Thank for suggestion. I might check with atom, too
