### ISSUE TITLE
Selecting column from bottom-left to top-right breaks cursor placement

### ISSUE THREAD

**Issue by timkelty** [bigfive/atom-sublime-select#78]
Results in cursor being placed on the line above instead of selection for the top line

![6a169f2886def0ba4639cda607c4fafa](https://cloud.githubusercontent.com/assets/18329/11874185/6ad7cb96-a4ac-11e5-9cf6-ebf767531448.gif)

Note: only happens if you drag **up** first. If you drag left first (and thus have a selection), it works fine.

**Comment by scott-vsi** [comment]
I see the same behavior if I drag from the top-right to the bottom-left as well. The cursor positions are no longer in the same column.

**Comment by bigfive** [comment]
This is a duplicate https://github.com/bigfive/atom-sublime-select/issues/40. I'll be concentrating on this for the next release
