### ISSUE TITLE
No longer working with middle mouse

### ISSUE THREAD

**Issue by looterz** [bigfive/atom-sublime-select#88]
After the latest update, I can no longer use this with my middle mouse button. Still works with alt, though.

**Comment by hellgiver** [comment]
I had to roll back to 1.3.0 to get it working.  I tried 1.5.1, 1.5.0, and 1.4.0; all of them did not work with middle click or alt/option on mac (I checked settings every time).  I am using Atom 1.5.0-beta0.

**Comment by bigfive** [comment]
To get middle mouse selection working, please use the following settings:

<img width="727" alt="screen shot 2016-01-21 at 10 15 02 am" src="https://cloud.githubusercontent.com/assets/633193/12469581/e829bcd0-c027-11e5-8104-901fc0ff4a73.png">

**Comment by karai17** [comment]
Disabling Key Trigger seems like an unsatisfying answer. I use both middle mouse and ctrl click all the time. Choosing between one or the other is not an option.

Being able to middle click and drag to select lines that are all in a row and being able to selectively click several lines not in a row are both very important use cases for this add-on. Please find a way to actually fix this.

**Comment by bigfive** [comment]
If I understand your meaning, the plugin has never been able to "selectively click several lines not in a row". Though I think atom perhaps has/had support for that.

I'm happy to receive PRs on this though, or to work on it as a feature if it proves to be a popular request.

**Comment by karai17** [comment]
Hm. Looks like I was wrong, then. I assumed your add-on provided that functionality, not Atom proper. All right then, this actually fixes the issue. Sorry, and thanks!
