### ISSUE TITLE
wrong behaviour on the opposite direction

### ISSUE THREAD

**Issue by mscaff0** [bigfive/atom-sublime-select#90]
If you select moving the mouse down it works as expected, but if you move the mouse up, some times you end up with the last line (the upper one) selected in a different column or even the entire line selected.

**Comment by derwentx** [comment]
Perhaps this is related to this issue, but i noticed that when I selected text in the reverse (bottom to top, right to left) direction, the top line would flicker for me. OSX atom 1.74 / SSCS 1.5.1

**Comment by RyanZim** [comment]
@bigfive Wasn't this fixed by #93?

BTW, any idea when that will be released?

**Comment by signalwerk** [comment]
@RyanZim @bigfive This was fixed by #93 but unfortunately the package is still on Version 1.5.1. If you wanna get the fix then you need to get it from the head (for example by doing: `apm install bigfive/atom-sublime-select`). then it works.

**Comment by jdw1996** [comment]
On both OS X and Ubuntu I was prompted to upgrade this package today, to version 1.6.0, and it fixed this issue on both OSes.

**Comment by RyanZim** [comment]
@mscaff0 @bigfive Can you close as per @jdw1996?

**Comment by signalwerk** [comment]
@bigfive @jdw1996 thank you for pushing versoin 1.6.0 today. works as well for me.
