### ISSUE TITLE
Glitch on "Esc->Select All", column selection won't go away

### ISSUE THREAD

**Issue by alexchandel** [bigfive/atom-sublime-select#98]
### Steps to replicate:
1. Open a new tab
2. Type three lines, with the contents `1`, `2`, and `3` resp.
3. Use atom-sublime-select to select all three columns
4. Press `esc`, eliminating the selection
5. Press `Cmd+A` (or equivalent) to do the "Select All" command.
#### Expected:

The entire file is selected & highlighted with a single cursor, i.e. the normal "Select All" behavior.
#### Actual:

Column-selection comes back from the dead and restores what you originally selected.

**Comment by bigfive** [comment]
This is an issue with the Atom handles multiple cursors (this package just helps create the selections/cursors not how they behave once created). Its worth lodging this issue with Atom.

**Comment by alexchandel** [comment]
This actually seems to be fixed in 1.14.1
